WINDOW_WIDTH, WINDOW_HEIGHT = love.window.getDimensions
VIRTUAL_WIDTH, VIRTUAL_HEIGHT = love.window.getDimensions



SYSTEM_ACCEL = math.pi / 1024
MAX_RADIUS = VIRTUAL_HEIGHT / 4

HEART_COLOR_DELTA = 1/16

MIN_ALPHA_DIFF = 0.05

-- BPM = 60

MOON_RADIUS = 32

PLAYER_ACCEL
